/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Conexion.ConexionMysql;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.text.DecimalFormat;
import javax.swing.table.TableColumn;

public class Historial extends javax.swing.JFrame {

    int xMouse, yMouse;
    ConexionMysql cn1;
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;

    DefaultTableModel Cl = new DefaultTableModel();

    public Historial() {
        initComponents();
        setLocationRelativeTo(null);

        String Ids[] = {"Id", "nombre", "dni", "op_gravada", "igv", "importe", "pago", "vuelto", "fecha","hora"};
        Cl.setColumnIdentifiers(Ids);
        tblHistorial.setModel(Cl);
        cn1 = new ConexionMysql();
        conet = cn1.conectar();
        mostrar_historial();
        buscador();

        TableColumn columnToAdjust = tblHistorial.getColumnModel().getColumn(0);
        columnToAdjust.setPreferredWidth(40);
        TableColumn columnToAdjust1 = tblHistorial.getColumnModel().getColumn(1);
        columnToAdjust1.setPreferredWidth(200);
        TableColumn columnToAdjust2 = tblHistorial.getColumnModel().getColumn(2);
        columnToAdjust2.setPreferredWidth(110);
        TableColumn columnToAdjust3 = tblHistorial.getColumnModel().getColumn(3);
        columnToAdjust3.setPreferredWidth(105);
        TableColumn columnToAdjust4 = tblHistorial.getColumnModel().getColumn(4);
        columnToAdjust4.setPreferredWidth(65);
        TableColumn columnToAdjust5 = tblHistorial.getColumnModel().getColumn(5);
        columnToAdjust5.setPreferredWidth(80);
        TableColumn columnToAdjust6 = tblHistorial.getColumnModel().getColumn(6);
        columnToAdjust6.setPreferredWidth(50);
        TableColumn columnToAdjust7 = tblHistorial.getColumnModel().getColumn(7);
        columnToAdjust7.setPreferredWidth(60);
        TableColumn columnToAdjust8 = tblHistorial.getColumnModel().getColumn(8);
        columnToAdjust8.setPreferredWidth(130);
        TableColumn columnToAdjust9 = tblHistorial.getColumnModel().getColumn(9);
        columnToAdjust9.setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        txtAtras = new javax.swing.JLabel();
        Header1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtVentas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHistorial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Nombre", "Codigo", "Precio", "Cantidad", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistorial.getTableHeader().setResizingAllowed(false);
        tblHistorial.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblHistorial);
        if (tblHistorial.getColumnModel().getColumnCount() > 0) {
            tblHistorial.getColumnModel().getColumn(0).setResizable(false);
            tblHistorial.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblHistorial.getColumnModel().getColumn(1).setResizable(false);
            tblHistorial.getColumnModel().getColumn(2).setResizable(false);
            tblHistorial.getColumnModel().getColumn(3).setResizable(false);
            tblHistorial.getColumnModel().getColumn(4).setResizable(false);
            tblHistorial.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 840, 370));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial imagen.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 830, 140));

        btnAtras.setBackground(new java.awt.Color(0, 162, 92));

        txtAtras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAtras.setForeground(new java.awt.Color(255, 255, 102));
        txtAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAtras.setText("ATRAS");
        txtAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 40));

        Header1.setBackground(new java.awt.Color(255, 255, 255));
        Header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Header1MouseDragged(evt);
            }
        });
        Header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Header1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("VENTAS TOTALES");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVentas.setEnabled(false);
        txtVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentasActionPerformed(evt);
            }
        });
        jPanel2.add(txtVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseClicked
        int rpta;
        rpta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de salir?", "Salir", 0);
        if (rpta == 0) {
            Menu a = new Menu();
            a.show();
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_txtAtrasMouseClicked

    private void txtAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseEntered
        btnAtras.setBackground(new Color(0, 115, 65));
        txtAtras.setForeground(Color.white);
    }//GEN-LAST:event_txtAtrasMouseEntered

    private void txtAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseExited
        btnAtras.setBackground(new Color(0, 162, 92));
        txtAtras.setForeground(new Color(255, 255, 102));
    }//GEN-LAST:event_txtAtrasMouseExited

    private void Header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header1MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Header1MousePressed

    private void Header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header1MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Header1MouseDragged

    private void txtVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    void mostrar_historial() {
        String sql = "select * from ventas";
        try {
            conet = cn1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] ventas = new Object[10];
            modelo = (DefaultTableModel) tblHistorial.getModel();
            while (rs.next()) {
                ventas[0] = rs.getInt("id");
                ventas[1] = rs.getString("nombre");
                ventas[2] = rs.getInt("dni");
                ventas[3] = rs.getDouble("op_gravada");
                ventas[4] = rs.getDouble("igv");
                ventas[5] = rs.getDouble("importe");
                ventas[6] = rs.getDouble("pago");
                ventas[7] = rs.getDouble("vuelto");
                ventas[8] = rs.getString("fecha");
                ventas[9] = rs.getString("hora");
                modelo.addRow(ventas);
            }
            tblHistorial.setModel(modelo);
        } catch (Exception e) {
            System.out.println("ERROR TABLA DE VENTAS " + e);
        }

    }

    void buscador() {
        String sql = "SELECT SUM(importe) FROM ventas";
        try {
            conet = cn1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                double a = rs.getDouble(1);
                DecimalFormat decimalFormat = new DecimalFormat("###0.00");
                String numeroFormateado = decimalFormat.format(a);
                txtVentas.setText("   S/ "+numeroFormateado);
            } else {
                JOptionPane.showMessageDialog(null, "EL TOTAL NO FUCNIONA");
            }
        } catch (Exception e) {
            System.out.println("ERROR EN BRINDAR EL TOTAL " + e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header1;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JLabel txtAtras;
    private javax.swing.JTextField txtVentas;
    // End of variables declaration//GEN-END:variables
}
